### ISSUE TITLE
Use of Convert.ChangeType() prevents compilation due to usage of System.Decimal

### ISSUE THREAD

**Issue by braml42** [dot42/dot42#10]
Using Convert.ChangeType() prevents compilation because of usage of System.Decimal type, which is not supported in Dot42, eventhough no change to or from System.Decimal is requested. See issue https://github.com/dot42/dot42/issues/5.
This makes Convert.Change() completely unavailable.

Cause is a reference to System.Decimal() in the internal method ToType() (https://github.com/dot42/api/blob/master/System/Convert.cs#L2869) eventhough Decimal type is deactivated in the conversionTable (line 2778), making the call to convertValue.ToDecimal() completely unreachable.

Removing this part of the if-statement (line 2868..2869) clears the compile-time error. Any usage of System.Decimal will cause a runtime exception, but would have stranded during compile-time.

**Comment by OlafPettersson** [comment]
Decimal has been reimplemted using Java's BigDecimal class. This should fix this issue.
