### ISSUE TITLE
java.lang.Runtime exception at WebResponse resp = req.GetResponse()

### ISSUE THREAD

**Issue by frankrem** [dot42/dot42#12]
string soap = @"<?xml version=""1.0"" encoding=""utf-8""?>
        <soap:Envelope xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" 
        xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" 
        xmlns:soap=""http://schemas.xmlsoap.org/soap/envelope/"">
        <soap:Body><GetColorChangeCharge xmlns=""http://reps.catalystinnovations.net/"">
        <password>ujnvusk</password></GetColorChangeCharge></soap:Body>    </soap:Envelope>";

HttpWebRequest req = (HttpWebRequest)WebRequest.Create("http://www.someurl/service.asmx");
req.Headers.Add("SOAPAction", "http://www.someurl/GetColorChangeCharge");
req.ContentType = "text/xml; charset=utf-8";
req.Accept = "text/xml";
req.Method = "POST";

using (Stream stm = req.GetRequestStream())
{
    using (StreamWriter stmw = new StreamWriter(stm))
    {
        stmw.Write(soap);
    }
}

WebResponse resp = req.GetResponse();
Stream responsStream = resp.GetResponseStream();

**Comment by OlafPettersson** [comment]
This might have been fixed with the latest merge. Please reopen if the problem still persists.
