### ISSUE TITLE
Error	9	Error while compiling System.Boolean System.Convert::ToBoolean(System.Decimal) in System.Convert: Unexpected opcode 246 in Ⴃ.ႷႼႼႥ.

### ISSUE THREAD

**Issue by saadhass** [dot42/dot42#15]
i am using the API 11. In my code the problem is caused by:
Convert.ChangeType(dbValue, dataMap.FieldType, null)

if i use the API10, the problem disappears.

**Comment by OlafPettersson** [comment]
This has probably been fixed with the latest merge. Please reopen if the problem still exists.
