### ISSUE TITLE
reflection not working

### ISSUE THREAD

**Issue by saadhass** [dot42/dot42#16]
i tried to use reflection but it does not work. i can not get the fields or methods list for a class. i got 0 element from GetDeclaredFields() and GetDeclaredMethods().

**Comment by OlafPettersson** [comment]
This has been fixed with the latest merge. Reflection should work out of the box like it does in .NET in almost all cases. See BUGS_AND_LIMITATIONS.md for obscure corner cases with differences to normal .NET behaviour.
