### ISSUE TITLE
Can not load Android.Extension Project

### ISSUE THREAD

**Issue by axcl** [dot42/dot42#18]
D:\dot42\test\Sources\VStudio\VStudio.Extension.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\VStudio.Project.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\Layout\LayoutTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\Menu\MenuTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\Plurals\PluralsTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\StringArrays\StringArraysTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\Strings\StringsTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\Shape\ShapeTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\ViewAnimation\ViewAnimationTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\Style\StyleTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\AppWidget\AppWidget.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\Activity\ActivityTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ProjectTemplates\ApplicationProject\ApplicationProjectTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ProjectTemplates\ClassLibraryProject\ClassLibraryTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\ItemTemplates\Manifest\ManifestTemplate.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

D:\dot42\test\Sources\VStudio\VStudio.Extension.Android.csproj : error  : The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.  D:\dot42\test\Common\Build\BuildTools.MSBuildTasks.targets

I got these Error when i try to build Visual Studio Extension Project. Any help?

**Comment by OlafPettersson** [comment]
There have been a lot of changes to the build system with the latest merge. I also wrote up an INSTALLATION.md with build instructions.
If you still encounter the problem, please reopen the issue.
