### ISSUE TITLE
Problem starting a new Project

### ISSUE THREAD

**Issue by glcjr** [dot42/dot42#22]
I get an error when I try to create a new dot42 application project:

Error: this template attempted to load component assembly ‘dot42.VStudio.Project.Android, Version=1.0.1.82, Culture=neutral, PublicKeyToken=0a72796057571e65'. For more information on this problem and how to enable this template, please see documentation on Customising Project Template.

I am able to load from the samples directory perfectly fine.

**Comment by PeterLaudy** [comment]
Hi glcjr,

The dot42 assemblies are no longer signed since the project became open source. So it's strange that the tools try to load a signed assembly. Maybe some tools have not been replaced when you updated to the latest version. Could you try to uninstall dot42 and then reinstall it again?

Kind regards,

Peter Laudy.

**Comment by PeterLaudy** [comment]
Ah sorry. Don't try to reinstall. In the newly created project file (csproj file) there is a reference to the assembly which cannot be loaded. Open the file with an editor and remove the public key part from the reference (maybe you need to remove everything except the file name). Then try to rebuild the project.

**Comment by glcjr** [comment]
Unfortunately it wasn't even creating the files. Just an empty subdirectory. I found where the templates are kept and I tried to change it inside the template by extracting, editing and then compressing but it no longer recognized it as a project file. 

However I did find a workaround. I copied one of the samples and then opened up the copy then replaced the files in it with the template files that I had extracted (mainactivity, the r.cs, and layout) and then exported it as a template and then installed it in the dot42 template folder under 1033 and that works! Its not as fancy as the one that comes with dot42 since it has a generic icon but it works and that's the important thing. :)

**Comment by PeterLaudy** [comment]
Nice that you find a workaround. I will try to fix this at the end of the week and notify you as soon as the solution is available.

**Comment by glcjr** [comment]
I was looking around and noticed this: https://github.com/dot42/dot42/issues/1 That would be really cool if it gets implemented.

**Comment by OlafPettersson** [comment]
This should be fixed with the latest merge. If you still encounter the problem, please reopen the issue.
