### ISSUE TITLE
Java.Lang.VerifyError

### ISSUE THREAD

**Issue by sebastianhaba** [dot42/dot42#24]
Java.Lang.VerifyError: "Rejecting class com.Test2.__generated because it failed compile-time verification (declaration of 'com.Test2.__generated' appears in /data/app/com.Test2-2/base.apk)"

Everytime when I create new project and run it I got this exception

**Comment by OlafPettersson** [comment]
I'm closing this as the recent merge has fixed dozens of verification rejection. If you still encounter the problem, please reopen the issue.
