### ISSUE TITLE
Attributes not working

### ISSUE THREAD

**Issue by robot9706** [dot42/dot42#9]
I've tried 3 things:

1) Attribute with int property (value assigned in constructor) : no problem
2) Attribute with int property (value assigned with NamedParameter) : property has default value
3) Attribute with enum: fails at GetCustomAttributes()

Here's the link to the project if it's needed: http://www.mediafire.com/download/pcytbcbqkftg6dq/Dot42AttributesTest.zip

(English is not my native language...)

**Comment by OlafPettersson** [comment]
The .NET Attribute emulation has been complety rewritten, and should now support everything that is allowed in .NET.
